name: Generate Doxygen Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate Documentation
        run: |
          docker run -v.:/data greenbone/doxygen doxygen /data/doxygen/Doxyfile
      - name: Upload Documentation
        uses: actions/upload-artifact@v3
        with:
          name: doxygen-docs
          path: docs
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
