name: Generate Doxygen Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate Documentation
        run: |
          docker run -v.:/data greenbone/doxygen doxygen /data/doxygen/Doxyfile
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
